# Construct decrement tables that will be used in the valuations. 
# Model version 1.0


# Inputs:
  # "Inputs_Data/Data_ES2015.RData" for decrements. (Generated by Data_readDecrements.R)
  # "Inputs_Data/Data_initGenderRatios.RData", for gender ratios (Generated by Data_memberData_CAFR2017.R)


# Final outputs
 # 1. decrement_model
      


 # 2. mortality.post.model



# Notes
  # Treatment of inividual decrement tables
  # Note that no future improvements are assued yet. 
  #  - Mortality for active members 
  #  - Mortality for service retirees
  #  - Mortality for disability retirees

  # Retirement rates: use combined rates for elected and mandated members for model version 1
  #  Note the original tables assume all members would retire by age 70. 
  #   - Retirement rate: 1st year
  #   - Retirement rate: 2nd year
  #   - Retirement rate: afte 2nd year
  #   - Retirement rate: early retirement
  
  # Disability rates
  #  Compute total disability rates, and for now treat all disabilities as ordinary disabilities 
  #  Need to compare the value of accidental and ordinary disability benefits. 
  #   - Ordinary disability rates
  #   - Accidental disability rates

  #  Withdrawl rate for actives







get_decrements <- function(Tier_select,
                           Global_paramlist_ = Global_paramlist,
                           paramlist_ = paramlist){

  
# Tier_select <- paramlist$tier_select
# Global_paramlist_ = Global_paramlist
# paramlist_ = paramlist

assign_parmsList(Global_paramlist_, envir = environment())
assign_parmsList(paramlist_,        envir = environment())



#*************************************************************************************************************
#                                Global settings                       #####                  
#*************************************************************************************************************

# parameters needed for function
dir_data <- "Inputs_data/"
  
#*************************************************************************************************************
#                                Loading Experience study data                       #####                  
#*************************************************************************************************************


load(paste0(dir_data, "Data_ES2015.RData"))
load(paste0(dir_data, "Data_initGenderRatios_AV2016.RData"))

  
gratio <- init_genderRatios %>% as.data.frame()
rownames(gratio) <- gratio$type
gratio
gratio["actives", "pct_male"]
  

# #*************************************************************************************************************
# #                                Loading MP2015 data                      #                  
# #*************************************************************************************************************
# 
# # Import projection scale (scale BB-2D)
# 
# data_scale_M <- read_excel(paste0(dir_data, "MP2015/research-2015-mort-imp-scale-rates.xlsx"), sheet = "Male", skip = 1) %>% 
# 	filter(!is.na(Age)) %>% 
# 	mutate(Age = 20:120, 
# 				 gender = "male")
# names(data_scale_M) <- c("age",1951:2030,"gender")
# 
# 
# data_scale_F <- read_excel(paste0(dir_data, "MP2015/research-2015-mort-imp-scale-rates.xlsx"), sheet = "Female", skip = 1) %>%
# 	filter(!is.na(Age)) %>% 
# 	mutate(Age = 20:120, 
# 				 gender = "female")
# names(data_scale_F) <- c("age",1951:2030, "gender")
# 
# 
# 
# # Transform data to long format
# data_scale_M %<>% gather(year_match, scale.M, -age, -gender) %>% mutate(year_match = as.numeric((year_match)))
# data_scale_F %<>% gather(year_match, scale.F, -age, -gender) %>% mutate(year_match = as.numeric((year_match)))
# 
# 
# 
# # Expand the scales to 1915-2164
# # 1915: the year when a 120-year old retiree in 2015 was at age 20. 
# # 2235: the year when a 20-year old new entrant in 2115 will be at age 120.
# # The scale BB-2D covers year 1951-2030. Years before 1951 use the scale for 1951, and years after 2030 use the scale for 2030. 




#*************************************************************************************************************
#                                Prepare mortality tables                       #####                  
#*************************************************************************************************************

df_qxm_actives
df_qxm_disbRet
df_qxm_servRet


mortality_model_MP2015 <- 
	expand.grid(year = 1915:2120, age = range_age, gender = c("male", "female")) %>% 
	mutate(gender = as.character(gender),
		     year_match = ifelse(year < 1951, 1951, ifelse(year>2030, 2030, year))) %>% 
	left_join(df_qxm_actives %>% 
							gather(gender, qxm_actives, -age) %>% 
							mutate(gender = str_replace(gender, "qxm_actives_", "")),
						by = c("age", "gender")
	) %>%
	left_join(df_qxm_servRet %>% 
							gather(gender, qxm_servRet, -age) %>% 
							mutate(gender = str_replace(gender, "qxm_servRet_", "")),
						  by = c("age", "gender")
	) %>% 
	left_join(df_qxm_disbRet %>% 
							gather(gender, qxm_disbRet, -age) %>% 
							mutate(gender = str_replace(gender, "qxm_disbRet_", "")),
						  by = c("age", "gender")
	) %>% 
	group_by(year, gender) %>% 
	mutate(qxm_servRet   = ifelse(age <= 54, qxm_actives,   qxm_servRet),
				 qxm_disbRet   = ifelse(age <= 54, qxm_actives,   qxm_disbRet)
				 ) %>% 
	arrange(year, gender, age)



# Applying MP-2015 
mortality_model_MP2015 %<>% 
	left_join(data_scale_M, by = c("gender", "age", "year_match")) %>% 
	left_join(data_scale_F, by = c("gender", "age", "year_match")) %>% 
	mutate(scale = ifelse(gender == "male", scale.M, scale.F)) %>% 
	group_by(gender, age) %>% 
	mutate(
		# service retirees
		qxm_servRet_proj = ifelse(year >= 2014, qxm_servRet[year == 2014] *  cumprod(ifelse(year <= 2014, 1, 1 - scale)), NA),
		qxm_servRet_proj = ifelse(year < 2014,  qxm_servRet[year == 2014] * lead(order_by(-year, cumprod(ifelse(year > 2014, 1, 1/(1 - scale))))), qxm_servRet_proj),
		
		qxm_disbRet_proj = ifelse(year >= 2014, qxm_disbRet[year == 2014] *  cumprod(ifelse(year <= 2014, 1, 1 - scale)), NA),
		qxm_disbRet_proj = ifelse(year < 2014,  qxm_disbRet[year == 2014] * lead(order_by(-year, cumprod(ifelse(year > 2014, 1, 1/(1 - scale))))), qxm_disbRet_proj)
		
	) %>% 
	select(year, age, gender, qxm_actives, qxm_servRet_proj, qxm_disbRet_proj)



# Combine genders

mortality_model_MP2015 %<>% 
	gather(variable, value, -age, -year, -gender) %>% 
	ungroup() %>% 
	mutate(variable = paste0(variable, "_", gender),
				 gender = NULL) %>% 
	spread(variable, value) %>% 
	mutate(qxm_actives = qxm_actives_male * gratio["actives", "pct_male"] + qxm_actives_female * gratio["actives", "pct_female"],
				 qxm_servRet = qxm_servRet_proj_male * gratio["servRet", "pct_male"] + qxm_servRet_proj_female * gratio["servRet", "pct_female"],
				 qxm_disbRet = qxm_disbRet_proj_male * gratio["disbRet", "pct_male"] + qxm_disbRet_proj_female * gratio["disbRet", "pct_female"],
				 
				 qxm_servRet =  ifelse(age == max(age), 1, qxm_servRet),
				 qxm_disbRet =  ifelse(age == max(age), 1, qxm_disbRet)
	) %>% 
	mutate_all(funs(na2zero(.))) %>% 
	
	# Mortality for vested terminated workers: actives mortality before retirement age, and service retirees mortality thereafter.
	mutate(qxm_terms = ifelse(age < age_vben, qxm_actives, qxm_servRet))


mortality_model_MP2015 %<>% select(year, age, qxm_actives, qxm_servRet, qxm_disbRet, qxm_terms)

mortality_model_MP2015 









#*************************************************************************************************************
#                                Prepare Retirement rate                       #####                  
#*************************************************************************************************************

df_qxr_y1
df_qxr_y2
df_qxr_y2post
df_qxr_early

# Calculate weighted average rates
# fill lower and higher ages with 0. 

# Mandated and elected combined
retRates_model_EM <- data.frame(age = range_age) %>% 
  left_join(df_qxr_y1) %>% 
  left_join(df_qxr_y2) %>% 
  left_join(df_qxr_y2post) %>%
  left_join(df_qxr_early) %>% 
  mutate(qxr_y1_EM     = qxr_y1_male_EM * gratio["actives", "pct_male"]     + qxr_y1_female_EM * gratio["actives", "pct_female"],
         qxr_y2_EM     = qxr_y2_male_EM * gratio["actives", "pct_male"]     + qxr_y2_female_EM * gratio["actives", "pct_female"],
         qxr_y2post_EM = qxr_y2post_male_EM * gratio["actives", "pct_male"] + qxr_y2post_female_EM * gratio["actives", "pct_female"],
         qxr_early     = qxr_early_male * gratio["actives", "pct_male"]     + qxr_early_female * gratio["actives", "pct_female"]) %>% 
  select(age,
         qxr_y1_EM,
         qxr_y2_EM,
         qxr_y2post_EM,
         qxr_early) %>% 
  mutate_at(vars(-age), funs(ifelse(age %in% 40:71, ., 0)))
retRates_model_EM

# Elected
retRates_model_E <- data.frame(age = range_age) %>% 
  left_join(df_qxr_y1) %>% 
  left_join(df_qxr_y2) %>% 
  left_join(df_qxr_y2post) %>%
  left_join(df_qxr_early) %>% 
  mutate(qxr_y1_E     = qxr_y1_male_E * gratio["actives", "pct_male"]     + qxr_y1_female_E * gratio["actives", "pct_female"],
         qxr_y2_E     = qxr_y2_male_E * gratio["actives", "pct_male"]     + qxr_y2_female_E * gratio["actives", "pct_female"],
         qxr_y2post_E = qxr_y2post_male_E * gratio["actives", "pct_male"] + qxr_y2post_female_E * gratio["actives", "pct_female"],
         qxr_early     = qxr_early_male * gratio["actives", "pct_male"]     + qxr_early_female * gratio["actives", "pct_female"]) %>% 
  select(age,
         qxr_y1_E,
         qxr_y2_E,
         qxr_y2post_E,
         qxr_early) %>% 
  mutate_at(vars(-age), funs(ifelse(age %in% 40:71, ., 0)))
retRates_model_E

# Mandated
retRates_model_M <- data.frame(age = range_age) %>% 
  left_join(df_qxr_y1) %>% 
  left_join(df_qxr_y2) %>% 
  left_join(df_qxr_y2post) %>%
  left_join(df_qxr_early) %>% 
  mutate(qxr_y1_M     = qxr_y1_male_M * gratio["actives", "pct_male"]     + qxr_y1_female_M * gratio["actives", "pct_female"],
         qxr_y2_M     = qxr_y2_male_M * gratio["actives", "pct_male"]     + qxr_y2_female_M * gratio["actives", "pct_female"],
         qxr_y2post_M = qxr_y2post_male_M * gratio["actives", "pct_male"] + qxr_y2post_female_M * gratio["actives", "pct_female"],
         qxr_early     = qxr_early_male * gratio["actives", "pct_male"]     + qxr_early_female * gratio["actives", "pct_female"]) %>% 
  select(age,
         qxr_y1_M,
         qxr_y2_M,
         qxr_y2post_M,
         qxr_early) %>% 
  mutate_at(vars(-age), funs(ifelse(age %in% 40:71, ., 0)))
retRates_model_M


# retRates_model_EM
# retRates_model_E
# retRates_model_M


#*************************************************************************************************************
#                                Prepare disability                      #####                  
#*************************************************************************************************************

# compare accidental and ordinary disability rates
df_qxd %>% 
  mutate(acc_ord_male   = qxd_acc_male   / qxd_ord_male,
         acc_ord_female = qxd_acc_female / qxd_ord_female,
         acc_pct_male   = qxd_acc_male   / (qxd_acc_male + qxd_ord_male), 
         acc_pct_female = qxd_acc_female / (qxd_acc_female + qxd_ord_female)
         )
# The proportion of accidental disability in total disability is less than 20%


# Add up ordinary and accidental disability rates and calculate gender-weighted average rates. 
disbRates_model <- data.frame(age = range_age) %>% 
  left_join(df_qxd) %>% 
  mutate(qxd_male   = qxd_ord_male + qxd_acc_male, 
         qxd_female = qxd_ord_male + qxd_acc_female, 
         qxd = qxd_male * gratio["actives", "pct_male"] + qxd_female * gratio["actives", "pct_female"],
         qxd = na2zero(qxd)
         ) %>% 
  select(age, qxd)
  
disbRates_model



#*************************************************************************************************************
#                                Prepare withdrawal rates                     #####                  
#*************************************************************************************************************
max(df_qxt$yos)

termRates_model <- data.frame(yos = 0:(70 - min_age)) %>% 
  left_join(df_qxt) %>% 
  mutate(qxt = qxt_male * gratio["actives", "pct_male"] + qxt_female * gratio["actives", "pct_female"],
         qxt = ifelse(yos > max(df_qxt$yos), qxt[yos == max(df_qxt$yos)], qxt)) %>% 
  select(yos, qxt)

termRates_model





#*************************************************************************************************************
#                  Adjustments 1: combining retirement rates based on eligibility    ####
#*************************************************************************************************************

# To construct retirement rates that can be used in the model of NYCTRS, for each tier we need to combine various types of retirement 
# rates into a single column of retirement rates based on the retirement eligibility rule. Below we summarize the eligibility rules for
# Tier IV and Tier VI


# Tier IV Basic: t4a
  # Unreduced:
     # age >= 62 & yos >= 5, or
     # age >= 55 & yos >= 30,
  # Reduced: age >= 55, and yos >=5

# Tier IV in 55/25: t4b
  # Unreduced:
    # age >= 62 & yos >= 5, or
    # age >= 55 & yos >= 25,
  # Reduced: age >= 55, and yos >=5


# Tier IV in 55/27 not in UFT:(mainly before 2009.12) t4c
  # Unreduced:
    # age >= 62 & yos >= 5, or
    # age >= 55 & yos >= 27,
  # Reduced: age >= 55, and yos >=5

# Tier IV in 55/27 in UFT: (mainly after 2009.12) t4d
  # Unreduced:
    # age >= 62 & yos >= 5, or
    # age >= 55 & yos >= 27,
  # Reduced: age >= 55, and yos >=5


# Tier VI
  # Unreduced:
    # age >= 63 & yos >= 10, or
  # Reduced: age >= 55, and yos >= 10


# create 2 columns for each tier
 # elig_full_txx:  number of year of being eligible for full retirement benefits
 # elig_early_txx: number of year of being eligible for full retirement benefits; 
 #                 0 after being eligible for full retirement benefits
 
# Construct single column of retirement rates for each tier 
 # The elected rates are used for Tier 4 55/25 members; the Mandated rates are used for all else

retRates_model_tiers <- 
	expand.grid(age = range_age, 
							ea = range_ea) %>% 
	mutate(yos = age - ea) %>% 
	filter(age >= ea) %>% 
	group_by(ea) %>% 
	left_join(retRates_model_EM, by = "age") %>%                                  # retirement: elected and mandated
	left_join(retRates_model_E %>% select(-qxr_early), by = "age")  %>%           # retirement: elected
	left_join(retRates_model_M %>% select(-qxr_early), by = "age")  %>%           # retirement: mandated
	mutate(
		     # Full retirement 
		     elig_full_t4a = ifelse( (age >= 62 & yos >= 5) | 
			   					 					 	   (age >= 55 & yos >= 30), 
														      1, 0) %>% cumsum,
		     
		     elig_full_t4b = ifelse( (age >= 62 & yos >= 5) | 
		     												 (age >= 55 & yos >= 25), 
		     												  1, 0) %>% cumsum,
		    
		     elig_full_t4c = ifelse( (age >= 62 & yos >= 5) | 
		     												 (age >= 55 & yos >= 27), 
		     											  	1, 0) %>% cumsum,
		     
		     elig_full_t4d = ifelse( (age >= 62 & yos >= 10) | 
		     												 (age >= 55 & yos >= 27), 
		     										   		1, 0) %>% cumsum,
		     
		     elig_full_t6  = ifelse( age >= 63 & yos >= 10,  
		     											  	1, 0) %>% cumsum,
		     
		     # Early retirement 
		     elig_early_t4a = ifelse(elig_full_t4a, 0, ifelse(age >= 55 & yos >= 5,  1, 0) %>% cumsum),  
		     elig_early_t4b = ifelse(elig_full_t4b, 0, ifelse(age >= 55 & yos >= 5,  1, 0) %>% cumsum),  
		     elig_early_t4c = ifelse(elig_full_t4c, 0, ifelse(age >= 55 & yos >= 5,  1, 0) %>% cumsum),  
		     elig_early_t4d = ifelse(elig_full_t4d, 0, ifelse(age >= 55 & yos >= 10, 1, 0) %>% cumsum), 
		     elig_early_t6  = ifelse(elig_full_t6,  0, ifelse(age >= 55 & yos >= 10, 1, 0) %>% cumsum) 
	) %>% 
	mutate(
		qxr_t4a = case_when(
			elig_early_t4a != 0 ~ qxr_early,
			elig_full_t4a == 1  ~ qxr_y1_M,
			elig_full_t4a == 2  ~ qxr_y2_M,
			elig_full_t4a >  2  ~ qxr_y2post_M, 
			TRUE ~ 0),
		
		qxr_t4b = case_when(
			elig_early_t4b != 0 ~ qxr_early,
			elig_full_t4b == 1  ~ qxr_y1_E,
			elig_full_t4b == 2  ~ qxr_y2_E,
			elig_full_t4b >  2  ~ qxr_y2post_E, 
			TRUE ~ 0),
		
		qxr_t4c = case_when(
			elig_early_t4c != 0 ~ qxr_early,
			elig_full_t4c == 1  ~ qxr_y1_M,
			elig_full_t4c == 2  ~ qxr_y2_M,
			elig_full_t4c >  2  ~ qxr_y2post_M, 
			TRUE ~ 0),
		
		qxr_t4d = case_when(
			elig_early_t4d != 0 ~ qxr_early,
			elig_full_t4d == 1  ~ qxr_y1_M,
			elig_full_t4d == 2  ~ qxr_y2_M,
			elig_full_t4d >  2  ~ qxr_y2post_M, 
			TRUE ~ 0),
		
		qxr_t6 = case_when(
			elig_early_t6 != 0 ~ qxr_early,
			elig_full_t6 == 1  ~ qxr_y1_M,
			elig_full_t6 == 2  ~ qxr_y2_M,
			elig_full_t6 >  2  ~ qxr_y2post_M, 
			TRUE ~ 0)
	)




#*************************************************************************************************************
#                      Putting together decrements  ####
#*************************************************************************************************************

# Create decrement table and calculate probability of survival
decrement_model <- expand.grid(start_year = 1915:(init_year + nyear - 1) ,
															 age = range_age, 
															 ea = range_ea) %>% 
	mutate(yos = age - ea,
				 year = start_year + age - ea) %>% 
	filter(age >= ea) %>% 
	left_join(mortality_model_MP2015, by = c("year", "age"))   %>%                # mortality 
	left_join(termRates_model, by = "yos")   %>%                                  # termination
	left_join(disbRates_model, by = "age")   %>%                                  # disability
	left_join(retRates_model_tiers, by = c("ea", "age", "yos")) %>%                      # retirement: by tier
	select(start_year, ea, age, yos, everything())%>%          
	arrange(ea, age)  %>%
	colwise(na2zero)(.) %>% 
	group_by(start_year, ea) 

decrement_model




#*************************************************************************************************************
#                  Adjustments 2: Termination rates    ####
#*************************************************************************************************************

# Adjustment to term rates:
 # Coerce termination rates to 0 when eligible for early retirement or full retirement, or age >= age_vben 

decrement_model %<>% mutate(
	qxt_t4a = ifelse((elig_early_t4a == 0 & elig_full_t4a == 0) | age < age_vben, qxt, 0),
	qxt_t4b = ifelse((elig_early_t4b == 0 & elig_full_t4b == 0) | age < age_vben, qxt, 0),
	qxt_t4c = ifelse((elig_early_t4c == 0 & elig_full_t4c == 0) | age < age_vben, qxt, 0),
	qxt_t4d = ifelse((elig_early_t4d == 0 & elig_full_t4d == 0) | age < age_vben, qxt, 0),
	qxt_t6  = ifelse((elig_early_t6  == 0 & elig_full_t6  == 0) | age < age_vben, qxt, 0),
)



#*************************************************************************************************************
#                  Selecting Tier    ####
#*************************************************************************************************************

decrement_model %<>%
	mutate(qxr = !!rlang::sym(paste0("qxr_", Tier_select)),
				 qxt = !!rlang::sym(paste0("qxt_", Tier_select)),

			   elig_early = !!rlang::sym(paste0("elig_early_", Tier_select)),
				 elig_full  = !!rlang::sym(paste0("elig_full_",  Tier_select))
	)



#*************************************************************************************************************
#                  Modify retirement rates for the purpose of modeling    ####
#*************************************************************************************************************

# Adjustment to the decrement table:
  # Why  
  #   In Winklevoss, retirement is treated as an immediate event, that is, retirees would start receiving benefit payments
  # the same year when they retire. This is different from how diability and death benefits are treated, for which beneficiaries
  # start receiving benefits the next year disability/death occurs, and can cause difficulty in modeling retirement with multiple 
  # possible retirement ages (need to check). 
  #
  #   To facilitate modeling and maintain consistent treatment aross all types of benefits, 
  # we assume that retirement occurs at the end of year t-1 for those who start receiving benefits at the begining of year t. Since 
  # theoretically year end of t-1 and year begining of t is the same point of time, we maintained the same theoretical treatment of 
  # retirement in Winklevoss (retirement is a immediate event); while assigning the retirement event and benefit payment event into two model
  # periods allow retirement to be modeled the same manner as other benefit types. 
  
  #   Note that since retirement is assumed to occur at the year end of the previous year, the retirement rate of year t is applied to 
  # those who survived all other types of separation events (death, termination, disability).

  # How
  # 	Move qxr.a backward by 1 period.(qxr at t is now assigned to t - 1), the probability of retirement at t - 1 is qxr.a(t)*(1 - qxt.a(t-1) - qxm.a(t-1) - qxd.a(t-1))
  # For the age right before the max retirement age (r.max - 1), probability of retirement is 1 - qxm.a - qxd.a - qxt.a,
  # which means all active members who survive all other risks at (r.max - 1) will enter the status "retired" for sure at age r.max (and collect the benefit regardless 
  # whether they will die at r.max)      

# Notes on adjusting the retirement rates for modeling:
  # Move qxr.a backward by 1 period.(qxr at t is now assigned to t - 1), the probability of retirement at t - 1 is qxr.a(t) * (1 - qxt.a(t-1) - qxm.a(t-1) - qxd.a(t-1))
  # For the age right before the max retirement age (r.max - 1), probability of retirement is 1 - qxm.a - qxd.a - qxt.a,
  # which means all active members who survive all other risks at (r.max - 1) will enter the status "retired" for sure at age r.max (and collect the benefit regardless 
  # whether they will die at r.max)      

pct_ca <- 0 # pct.ca.M * pct.male + pct.ca.F * pct.female
pct_la <- 1 - pct_ca

decrement_model %<>% group_by(ea) %>%  
	mutate(qxr = ifelse(age == max_retAge - 1,
											1 - qxt - qxm_actives - qxd, 
											lead(qxr) * (1 - qxt - qxm_actives - qxd)), # Total probability of retirement
				 
				 qxr.la = ifelse(age == max_retAge, 0 , qxr * pct_la),  # Prob of opting for life annuity
				 qxr.ca = ifelse(age == max_retAge, 0 , qxr * pct_ca),  # Prob of opting for contingent annuity
				 
				 # qxd.la = ifelse(age == r.max, 0 , qxd * pct.la),  # Prob of opting for life annuity
				 # qxd.ca = ifelse(age == r.max, 0 , qxd * pct.ca)
				 
				 # qxd.la = ifelse(age == r.max, 0 , qxd * 1),  # Prob of opting for life annuity
				 # qxd.ca = ifelse(age == r.max, 0 , qxd * 0)
				 
	)   


######!!!! need to construct retirement age dependent mortality for life annuitants.
# For retired(".r"), the only target status is "dead". Note that in practice retirement mortality may differ from the regular mortality.
#mutate(qxm.la.r   = qxm.r) 


#*************************************************************************************************************
#                  Compute various survival rates  ####
#*************************************************************************************************************

decrement_model %<>% 
	group_by(start_year, ea) %>% 
	mutate( 
		      # pxm: probability of survival
		      pxm_actives = 1 - qxm_actives,
					pxm_disbRet = 1 - qxm_disbRet,
					pxm_servRet = 1 - qxm_servRet,
					pxm_terms   = 1 - qxm_terms,
					
					pxT     = 1 - qxt - qxd - qxm_actives - qxr, 
					
					# prob of surviving up to age_vben, the age vested terminated members can start claiming benefits.
					# Note that mortality for active members is applied to vested terminated members. 
					px_r.vben_m = order_by(-age, cumprod(ifelse(age >= age_vben, 1, pxm_terms)))  
					
					# The following are legacy codes from model version that only allow for a single retirement age.
					# pxRm        = order_by(-age, cumprod(ifelse(age >= r.max, 1, pxm.pre))), # prob of surviving up to r.max, mortality only
					        
					# px65T = order_by(-age, cumprod(ifelse(age >= r.max, 1, pxT))), # prob of surviving up to r.max, composite rate
					# p65xm = cumprod(ifelse(age <= r.max, 1, lag(pxm))))            # prob of surviving to x from r.max, mortality only
	) %>% 
	ungroup() %>% 
	mutate_all(funs(na2zero))


#*************************************************************************************************************
#                 selecting variables  ####
#*************************************************************************************************************

# decrement_model %>% names

decrement_model %<>% 
	select(start_year, ea, age, yos,
				 qxm_actives,
				 qxm_servRet,
				 qxm_disbRet,
				 qxm_terms,
				 qxt,
				 qxd,
				 qxr,
				 elig_early,
				 elig_full,
				 qxr.la,
				 qxr.ca,
				 pxm_actives,
				 pxm_disbRet,
				 pxm_servRet,
				 pxm_terms,
				 pxT,
				 px_r.vben_m)


return(decrement_model)

}




