# Imputation of the yos distribution of active members based on CAFR data

# Inputs:
#		1. Inputs_data/Data_DemoCAFR17.RData     (generated by NYCTRS_Data_readDemoCAFR17.R)
#		2. Inputs_data/Data_ImputedActives.RData (generated by NYCTRS_Data_ImputationActives.R)

# Outputs:
#   


#*********************************************************************************************************
#                      ## Global settings  ####
#*********************************************************************************************************

dir_data  <- "Inputs_data/"

#*********************************************************************************************************
#                      ##  Loading data  ####
#*********************************************************************************************************

load(paste0(dir_data, "Data_DemoCAFR17.RData"))
load(paste0(dir_data, "Data_ImputedActives.RData"))



#*********************************************************************************************************
#                      ##  Exploring spreading the cells    ####
#*********************************************************************************************************

# Interpolation of actives
fillin.actives.spreadyos.splineage <- function(lactives) {
	# salary:
	#   first spread uniformly within age.cell-yos.cell group (same salary for all)
	#   then for every yos, estimate salary for each age using a spline - adjust endpoints first for plausibility
	#   finally, adjust resulting salary within each age.cell-yos.cell proportionately to hit total payroll values from grouped data
	#   then add ea to the data
	# nactives: spread uniformly within age.cell-yos.cell group (same nactives for all), then add ea to the data
	
	lactives
	
	adf <- lactives$actives.yos
	agecuts <- lactives$agecuts
	yoscuts <- lactives$yoscuts
	#eacuts <- lactives$eacuts
	minage <- min(agecuts$agelb)
	maxage <- max(agecuts$ageub)
	minyos <- min(yoscuts$yoslb)
	maxyos <- max(yoscuts$yosub)
	
	planname <- paste0(adf$planname[1])
	
	# adf %>% select(age, ea, salary) %>% spread(ea, salary)
	# adf %>% select(age, ea, nactives) %>% spread(ea, nactives)
	
	# create a master grouped data frame
	adf.g <- adf %>% select(-planname, -age, -yos, nactives.cell=nactives, salary.cell=salary) %>%
		mutate(pay.cell=nactives.cell * salary.cell) %>%
		mutate(ageidx = findInterval(age.cell, agecuts$agelb),
					 age.lb = agecuts$agelb[ageidx],
					 age.ub = agecuts$ageub[ageidx],
					 yosidx = findInterval(yos.cell, yoscuts$yoslb),
					 yos.lb = yoscuts$yoslb[yosidx],
					 yos.ub = yoscuts$yosub[yosidx]) %>%
		select(age.cell, yos.cell, age.lb, age.ub, yos.lb, yos.ub, nactives.cell, salary.cell, pay.cell)
  
  adf.g	

	# expand the grouped data frame to all allowable age-yos combinations ####
	xpnd <- function(df) {
		# expand to all age-yos combinations but only keep those where ea>=15 or, if there are no such records,
		# keep the recrods with max ea
		df2 <- expand.grid(age=df$age.lb:df$age.ub, yos=df$yos.lb:df$yos.ub) %>%
			mutate(ea=age - yos) %>%
			filter((ea >= 20) | (ea<20 & ea==max(ea))) %>%
			select(-ea)
		return(df2)
	}
	
	adf.x <- adf.g %>% rowwise() %>%
		do(cbind(., xpnd(.))) %>%
		ungroup %>%  # get rid of rowwise
		group_by(age.cell, yos.cell) %>%
		mutate(n.cell=n()) %>%
		select(age, yos, everything()) %>%
		arrange(age, yos)
	
	
	# work with the expanded data ####
	
	# we have to anchor the endpoints with reasonable values BEFORE computing the spline
	adjustends <- function(age, salary) {
		# the basic idea is that if an endpoint is NA, insert a plausible value
		
		# simple rule: if spline first or last value falls within +/ 50% of the nearest nonNA value, use spline estimate
		# otherwise use the capped value
		firstnonna <- salary[which.min(is.na(salary))]
		lastnonna <- rev(salary)[which.min(is.na(rev(salary)))]
		bound <- .5
		firstrange <- c(firstnonna * bound, firstnonna * (1 + bound))
		lastrange <- c(lastnonna * bound, lastnonna * (1 + bound))
		cap <- function(sal, range) {
			cappedval <- max(sal, range[1])
			cappedval <- min(cappedval, range[2])
			return(cappedval)
		}
		
		salary.est <- spline(age, salary, xout=age)$y # what does spline think naively?
		salary.adjusted <- salary
		
		if(is.na(salary[1])) salary.adjusted[1] <- cap(salary.est[1], firstrange)
		ilast <- length(salary)
		if(is.na(salary[ilast])) salary.adjusted[ilast] <- cap(salary.est[ilast], firstrange)
		
		return(salary.adjusted)
	}
	
	# test out adjustends
	# fs <- function(age, sal) return(spline(age, sal, xout=age)$y) # spline doesn't seem to work with dplyr if not in function
	# # various salaries to try out
	# salary <- seq(20, 50, length.out = 10)
	# salary <- c(20, NA, 30, NA, 40, NA, 50, NA, NA, 80)
	# salary <- c(20, NA, 30, NA, 40, NA, 50, NA, NA, 30)
	# salary <- c(NA, NA, 30, NA, 40, NA, 50, NA, NA, 30)
	# salary <- c(NA, NA, 30, NA, 40, NA, 50, NA, NA, NA)
	# salary <- c(NA, 10, 30, NA, 40, NA, 50, 80, NA, NA)
	# age <- 21:30
	# d <- data_frame(age, salary, saladj=adjustends(age, salary)) %>%
	#   mutate(sal.spline=fs(age, salary),
	#          saladj.spline=fs(age, saladj))
	# d
	# qplot(age, value, data=gather(d, variable, value, -age), colour=variable, geom=c("point", "line")) + scale_x_continuous(breaks=0:100) + geom_hline(y=0)
	
	
	spline.y2 <- function(age, salary, safesalary) {
		# safesalary is what we use if salary has no data
		if(all(is.na(salary))) {
			print("AllNA")
			salary <- safesalary
		}
		salary.adjusted <- adjustends(age, salary)
		
		sp.out <- spline(age, salary.adjusted, xout=age)
		salout <- sp.out$y
		return(salout)
	}
	
	adf.x3 <- adf.x %>% ungroup %>% # MUST be ungrouped or ifelse won't work if there is only one rec in a group
		mutate(nactives=nactives.cell / n.cell, # always spread nactives uniformly
					 salary.group=ifelse(age==age.cell & yos==yos.cell, salary.cell, NA),
					 salary.group=ifelse(salary.group==0, NA, salary.group),
					 salary.agecell=ifelse(age==age.cell, salary.cell, NA)) %>% # Yimeng's first step
		group_by(yos) %>%
		arrange(age) %>%
		mutate(salary.spline.adjep=spline.y2(age, salary.agecell, salary.cell)) %>% # Yimeng's 2nd step with endpoint adjustment
		group_by(age.cell, yos.cell) %>%
		mutate(planname=planname,
					 pay.unadj=sum(salary.spline.adjep * nactives),
					 adjust=pay.cell / pay.unadj,
					 salary.final=salary.spline.adjep * adjust,
					 pay.adj=sum(salary.final * nactives),
					 ea=age - yos
					 #ea.cell=eacuts$stub[findInterval(ea, eacuts$lb)]
		)
	
	return(adf.x3)
}

# data structure of the input list of fillin.actives.spreadyos.splineag
	# list name: lactives
	# $agecuts:
	#   - age.cell
	#   - agelb
	#   - ageub
	# $yoscuts:
	#   - yos.cell
	#   - yoslb
	#   - yosub
	# $actives.yos
	#   - age.cell
	#   - yos.cell
	#   - age
	#   - yos
	#   - planname
	#   - nactives
	#   - salary


# Interpolation of retirees
fillin.retirees <- function(list_data) {
	
	rdf <- select(list_data$data, planname, age, N, V) # keep only the vars we want
	agecuts <- list_data$agecuts
	
	planname <- paste0(rdf$planname[1], "_fillin")
	name_N <- list_data$varNames["name_N"]
	name_V <- list_data$varNames["name_V"]
	
	# add group ranges to the retirees data frame
	combo <- rdf %>%
		mutate(totben=N * V) %>%
		mutate(ageidx=findInterval(age, agecuts$agelb),
					 age.lb=agecuts$agelb[ageidx],
					 age.ub=agecuts$ageub[ageidx]) %>%
		arrange(age)
	
	# get avg benefits by age, via spline
	avgben <- splong(select(combo, age, V), "age", min(combo$age.lb):max(combo$age.ub))
	# force benefit to be non-negative DJB added 10/30/2015
	avgben <- avgben %>% mutate(V=ifelse(V<0, 0, V))
	
	guessdf <- data.frame(age=min(combo$age.lb):max(combo$age.ub)) %>%
		mutate(ageidx=findInterval(age, agecuts$agelb),
					 age.cell=combo$age[match(ageidx, combo$ageidx)],
					 N.cell=combo$N[match(ageidx, combo$ageidx)],
					 V.cell=combo$V[match(ageidx, combo$ageidx)]) %>%
		group_by(age.cell) %>%
		mutate(n.cell=n(),
					 N=N.cell / n.cell, # spread nretirees evenly
					 adjV=avgben$V[match(age, avgben$age)], # get the spline-based avg benefit
					 adjtotben=N * adjV)
	
	# refine the guess by adjusting ensure that we hit the right total benefits in each group
	guessdf2 <- guessdf %>% group_by(age.cell) %>%
		mutate(adjust=mean(N.cell * V.cell) / sum(adjtotben),
					 V=adjV*adjust,
					 totben=N * V)
	
	rdf.fillin <- guessdf2 %>% mutate(planname=planname) %>%
		select(planname, age.cell, age, N, V) %>%
		ungroup
	#plyr::rename(c("N" = list_data$varNames["name_N"])))
	
	names(rdf.fillin)[names(rdf.fillin) == "N"] <- name_N
	names(rdf.fillin)[names(rdf.fillin) == "V"] <- name_V
	
	return(rdf.fillin)
}

# data structure of the input list of fillin.actives.spreadyos.splineag
  # list name: ldata
  # $agecuts:
  #   - age.cell
  #   - agelb
  #   - ageub
  # $yoscuts:
  #   - yos.cell
  #   - yoslb
  #   - yosub
  # $data
  #   - age.cell
  #   - age
  #   - planname
  #   - N
  #   - V
  # $varNames
  #   - name_N
  #   - name_V  

planName <- "NYCTRS_CAFR17"

get_agecuts <- function(df){
	df %>% 
		mutate(age.cell = (age_lb + age_ub)/ 2) %>% 
		select(age.cell, agelb = age_lb, ageub = age_ub) 
}


#*********************************************************************************************************
#                    1.  Initial actives   ####
#*********************************************************************************************************

# The output data frame includes active members of all tiers.
# May need to break it down later when modeling tiers separately. 


# Prepare data for the interpolation function
lactives <- list(
	agecuts = agecuts,
	yoscuts = yoscuts,
	actives.yos = 
		df_actives_impt_CAFR17 %>%
		select(
			planname = plan,
			age.cell,
			yos.cell,
			nactives = nactives_impt,
			salary   = salary_impt
		) %>%
		mutate(age = age.cell, yos = yos.cell)
)
lactives

# Grouped data
actives_grouped <-
	lactives$actives.yos %>% 
	ungroup %>% 
	select(planname, age, yos, nactives, salary) %>%
	mutate(planname = paste0(planname, "_grouped"),
				 ea = age - yos)

# interpolated data
actives_fillin <-
	fillin.actives.spreadyos.splineage(lactives) %>% 
	ungroup %>%
	select(planname, age, yos, ea,
				 #age.cell, yos.cell,
				 nactives, salary = salary.final) %>%
	mutate(planname = paste0(planname, "_fillin"))


# Combining results:
init_actives <- actives_fillin  # bind_rows(actives_fillin, actives_grouped)
init_actives

# Examine results
actives_fillin_spread <-
	actives_fillin %>%
	select(age, yos, nactives) %>%
	spread(yos, nactives)

salary_fillin_spread <-
	actives_fillin %>%
	select(age, yos, salary) %>%
	spread(yos, salary)

actives_fillin %>%
	summarise(avg.sal = sum(nactives * salary) / sum(nactives))


#*********************************************************************************************************
#                    2.  Initial Retirees   ####
#*********************************************************************************************************

ldata_servRet <- list(
	data =
		df_nservRet %>%
		mutate(
			nservRet = nservRet_male + nservRet_female,
			benefit  = (nservRet_male * benefit_male + nservRet_male * benefit_male) / nservRet,
			age.cell = (age_lb + age_ub) / 2,
			planname = planName
		) %>%
		mutate_all(funs(ifelse(is.nan(.), 0, . ))) %>% 
		select(age.cell, N = nservRet, V = benefit, planname) %>% 
		mutate(age = age.cell) %>% 
		as.data.frame(), # otherwise, would lead to error in function splong
	
	agecuts = get_agecuts(df_nservRet) %>% as.data.frame(),
	
	varNames =
		tibble(name_N = "nservRet", name_V = "benefit_servRet")
)


init_servRet <- fillin.retirees(ldata_servRet) %>% mutate_all(funs(ifelse(is.nan(.), 0, . ))) 
init_servRet
	


#*********************************************************************************************************
#                    3.  Initial survivors   ####
#*********************************************************************************************************

df_nsurvivors

ldata_survivors <- list(
	data =
		df_nsurvivors %>%
		mutate(
			nsurvivors = nsurvivors_male + nsurvivors_female,
			benefit  = (nsurvivors_male * benefit_male + nsurvivors_male * benefit_male) / nsurvivors,
			age.cell = (age_lb + age_ub) / 2,
			planname = planName
		) %>%
		mutate_all(funs(ifelse(is.nan(.), 0, . ))) %>% 
		select(age.cell, N = nsurvivors, V = benefit, planname) %>% 
		mutate(age = age.cell) %>% 
		as.data.frame(), # otherwise, would lead to error in function splong
	
	agecuts = get_agecuts(df_nsurvivors) %>% as.data.frame(),
	
	varNames =
		tibble(name_N = "nsurvivors", name_V = "benefit_survivors")
)
ldata_survivors


init_survivors <- fillin.retirees(ldata_survivors) %>% mutate_all(funs(ifelse(is.nan(.), 0, . ))) 
init_survivors



#*********************************************************************************************************
#                    4.  Initial disability retirees   ####
#*********************************************************************************************************

# adding accidental and ordinary disability retirees 

df_ndisbRet <- left_join(
	df_ndisbRet_acc %>% 
		mutate(
			ndisbRet_acc = ndisbRet_acc_male + ndisbRet_acc_female,
			benefit_acc  = (ndisbRet_acc_male * benefit_male + ndisbRet_acc_female * benefit_female) / ndisbRet_acc) %>% 
		select(age_lb, age_ub, ndisbRet_acc, benefit_acc),
		
	df_ndisbRet_ord %>% 
		mutate(
			ndisbRet_ord = ndisbRet_ord_male + ndisbRet_ord_female,
			benefit_ord  = (ndisbRet_ord_male * benefit_male + ndisbRet_ord_female * benefit_female) / ndisbRet_ord) %>% 
		select(age_lb, age_ub, ndisbRet_ord, benefit_ord)
)

df_ndisbRet %<>% 
	mutate(ndisbRet   = ndisbRet_acc + ndisbRet_ord,
				 benefit = (ndisbRet_acc * benefit_acc + ndisbRet_ord * benefit_ord) / ndisbRet
				 ) %>% 
	mutate_all(funs(ifelse(is.nan(.), 0, .))) %>% 
	select(age_lb, age_ub, ndisbRet, benefit)
df_ndisbRet



ldata_disbRet <- list(
	data =
		df_ndisbRet %>%
		mutate(
			age.cell = (age_lb + age_ub) / 2,
			planname = planName
		) %>%
		mutate_all(funs(ifelse(is.nan(.), 0, . ))) %>% 
		select(age.cell, N = ndisbRet, V = benefit, planname) %>% 
		mutate(age = age.cell) %>% 
		as.data.frame(), # otherwise, would lead to error in function splong
	
	agecuts = get_agecuts(df_ndisbRet) %>% as.data.frame(),
	
	varNames =
		tibble(name_N = "ndisbRet", name_V = "benefit_disbRet")
)
ldata_disbRet


init_disbRet <- fillin.retirees(ldata_disbRet) %>% mutate_all(funs(ifelse(is.nan(.), 0, . ))) 
init_disbRet



#*********************************************************************************************************
#                    5.  Gender ratio   ####
#*********************************************************************************************************
# This will be used for constructing decrement tables


init_genderRatios <- 
	bind_rows(
			
		   df_nactives %>% 
				summarise(num_male = sum(nactives_male),
									num_female = sum(nactives_female)) %>% 
				mutate(pct_male = num_male / (num_male + num_female), 
							 pct_female = 1 - pct_male,
							 planname = planName,
							 type = "actives"),
			
			
			df_nservRet %>% 
				summarise(num_male = sum(nservRet_male),
									num_female = sum(nservRet_female)) %>% 
				mutate(pct_male = num_male / (num_male + num_female), 
							 pct_female = 1 - pct_male,
							 planname = planName,
							 type = "serRet"),
			
			
			df_nsurvivors %>% # why share share of female so high for survivors?
				summarise(num_male = sum(nsurvivors_male),
									num_female = sum(nsurvivors_female)) %>% 
				mutate(pct_male = num_male / (num_male + num_female), 
							 pct_female = 1 - pct_male,
							 planname = planName,
							 type = "survivors"),
			
			
			bind_cols(
				select(df_ndisbRet_acc, ndisbRet_acc_male, ndisbRet_acc_female),
				select(df_ndisbRet_ord, ndisbRet_ord_male, ndisbRet_ord_female)
				) %>% 
				mutate(ndisbRet_male   = ndisbRet_acc_male, ndisbRet_ord_male,
							 ndisbRet_female = ndisbRet_acc_female, ndisbRet_ord_female) %>% 
				summarise(num_male = sum(ndisbRet_male),
									num_female = sum(ndisbRet_female)) %>% 
				mutate(pct_male = num_male / (num_male + num_female), 
							 pct_female = 1 - pct_male,
							 planname = planName,
							 type = "disbRet")
	) %>% 
	select(planname, type, everything())

init_genderRatios




#*********************************************************************************************************
#                    6.  save results   ####
#*********************************************************************************************************

init_actives
init_servRet
init_survivors
init_disbRet

save(
	init_actives,
	init_servRet,
	init_survivors,
	init_disbRet,
	file = paste0(dir_data, "Data_initDemographics_CAFR17.RData")
)

save(init_genderRatios, 
		 file = paste0(dir_data, "Data_initGenderRatios.RData")
)

#*********************************************************************************************************
#                    7.  examination   ####
#*********************************************************************************************************

df_TierShares

ntot <- init_actives$nactives %>% sum  # 118201
nyos2 <- filter(init_actives, yos <=2)$nactives %>% sum
nyos3 <- filter(init_actives, yos <=3)$nactives %>% sum
nyos4 <- filter(init_actives, yos <=4)$nactives %>% sum

nyos2/ntot # 19.6%
nyos3/ntot # 25.9%, 
nyos4/ntot # 32.1%

# share of Tier 6 CAFR2017 ep163
# (FY or calendar year? year start or year end? should FY end. 
#  Would match better if it is FY start, but does not make sense for 2012)
 # 2015: 17.4%
 # 2016: 17.9%
 # 2017: 27.6%

# if use yos <= 3 as the cutting point, would assign too many people to Tier 6 (25.9% vs 17.9%)


