# Imputation of the yos distribution of active members based on CAFR data

# Inputs:
#		1. Inputs_data/Data_DemoCAFR17.RData, df_nactives  (generated by NYCTRS_Data_readDemoCAFR17.R)
#		2. Inputs_data/Scale_largePlans.RData (generated by NYCTRS_Data_demoLargePlans.R)

# Outputs:
#   Imputed distributions of active members and salary (in 5-year groups)


#*********************************************************************************************************
#                      ## Global settings  ####
#*********************************************************************************************************

dir_data  <- "Inputs_data/"



#*********************************************************************************************************
#                      ## 1. Loading data  ####
#*********************************************************************************************************

load(paste0(dir_data, "Data_DemoCAFR17.RData"))
load(paste0(dir_data, "Scales_largePlans.RData"))


#*********************************************************************************************************
#   Imputation    ####
#*********************************************************************************************************

# Number of actives and salary by age, from CAFR
df_actives_byAge <-
	df_nactives %>%
	mutate(
		plan = "NYCTRS_CAFR17",
		age.cell = age_lb + 2,
		nactives = nactives_male + nactives_female,
		salary  = (nactives_male * salary_male + nactives_female * salary_female) / (nactives_male + nactives_female),
		sal.avg = sum((nactives_male + nactives_female) * salary) / sum(nactives_male + nactives_female),
		sal.scale = salary / sal.avg
	) %>%
	select(plan, age.cell, nactives, salary, sal.avg)
df_actives_byAge


type_weight_nact <- "s"
type_weight_sal  <- "s1"

scaleName_nact <- paste0("nactives_share_", type_weight_nact)
scaleName_sal  <- paste0("sal.scale_",      type_weight_sal)

# Scales
scale_largePlans <-
	left_join(scale_nactives_largePlans, scale_salary_largePlans) %>%
	select(age.cell,
				 yos.cell,
				 scale_nact = !!scaleName_nact,
				 scale_sal  = !!scaleName_sal)
scale_largePlans

df_actives_impt_CAFR17 <-
	scale_largePlans %>%
	left_join(df_actives_byAge) %>%
	group_by(age.cell) %>%
	mutate(
		nactives_impt = nactives * scale_nact / sum(scale_nact, na.rm = TRUE),
		salary_impt   = scale_sal * salary * sum(nactives_impt) / sum(scale_sal * nactives_impt),
		type_weight_nact = type_weight_nact,
		type_weight_sal  = type_weight_sal
	) %>% 
	select(plan, age.cell, yos.cell, type_weight_nact, type_weight_sal, nactives_impt, salary_impt)

df_actives_impt_CAFR17
	

# Double check
df_actives_impt %>% # average salary by group
	left_join(df_actives_byAge) %>% 
	group_by(age.cell) %>%
	summarize(
		sal.avg = sum(nactives_impt * salary_impt) / sum(nactives_impt),
		sal.TRS = unique(salary),
		diff = sal.avg/sal.TRS - 1
	)

df_actives_impt %>% ungroup %>% # Overall average Target: 78038.98
	summarize(sal.avg = sum(nactives_impt * salary_impt) / sum(nactives_impt))

#*********************************************************************************************************
#   Save results    ####
#*********************************************************************************************************

save(df_actives_impt_CAFR17, file = paste0(dir_data, "Data_ImputedActives"))
















