

# Inputs:
#		1. Inputs_data/Data_MemberData_spread_AV2016.RData     (generated by NYCTRS_Data_readMemberData_AV2016.R)
         # - init_actives
         # - init_disbRet
         # - init_servRet
         # - init_survivors
         # - init_terms




# Outputs:
#   



# Task 1: allocating active members into 3 tiers.

## Determination of Tier members 
 # - Step 1: Tier 6. 
 #    - Max YOS is 4  years and 3 months. 
 #    - Consider all members in the 0-4 YOS group as Tier 6 members 
 # - Step 2: 55/27 program. 
 #    - Max YOS is 9 year and 4 month, min YOS 4 years and 4 month.  
 #    - Consider all members in the 5-9 YOS group as Tier 4 55/27 members
 # - Step 3: Tier 4 basic and Tier 4 55/25
 #    - There are about 60k members with YOS >= 10. 
 #    - For YOS >= 10, the number of 55/25 members is approximately  44,918 - 21445=23473 
 #    - Make assumption on how 55/25 members are distributed in YOS >= 10 members. For now even distribution
 # - Step 4: constructing tiers
 #    - T4a: tier 4 basic
 #    - T4b: tier 4 55/25 and tier 4 55/27
 #    - T6 : tier 6


## Task 2: Merging survivors into service retirees  


#*********************************************************************************************************
#                      ## Global settings  ####
#*********************************************************************************************************

dir_data  <- "Inputs_data/"


t6_minYOS <- 0
t6_maxYOS <- 4

t4_5527_minYOS <- 5
t4_5527_maxYOS <- 9

t4_basic_minYOS <- 10    # including 55/25 members 
t4_basic_maxYOS <- Inf   # including 55/25 members

nactives_55program <- 44918  # number of 55/25 and 55/27 members (TRS FOIL)


#*********************************************************************************************************
#                      ##  Loading data  ####
#*********************************************************************************************************
load(paste0(dir_data, "Data_MemberData_spread_AV2016.RData"))





#*********************************************************************************************************
#                      ##  Exploring spreading the cells    ####
#*********************************************************************************************************

init_actives_tiers <- 
	init_actives %>% 
	mutate(nactives_t6        = ifelse(yos >= t6_minYOS & yos <= t6_maxYOS, nactives, 0),
				 salary_t6          = ifelse(yos >= t6_minYOS & yos <= t6_maxYOS, salary,   0),
				 nactives_t4_5527   = ifelse(yos >= t4_5527_minYOS & yos <= t4_5527_maxYOS, nactives, 0),
				 salary_t4_5527     = ifelse(yos >= t4_5527_minYOS & yos <= t4_5527_maxYOS, salary,   0),
         nactives_t4_basic  = ifelse(yos >= t4_basic_minYOS & yos <= t4_basic_maxYOS, nactives, 0),
				 salary_t4_basic    = ifelse(yos >= t4_basic_minYOS & yos <= t4_basic_maxYOS, salary,   0)
				 )

# Infer number of 55/25 members in nactives_t4_basic

nactives_t4_5525 <- nactives_55program - sum(init_actives_tiers$nactives_t4_5527)

share_t4_5525inBasic = nactives_t4_5525 / sum(init_actives_tiers$nactives_t4_basic)
share_t4_5525inBasic 

# About 39.3% of the members in nactives_t4_basic are in 55/25 program
# For now, assumed 
#   - 1. 55/25 members accounts for the same share in all age-yos combos. 
#   - 2. 55/25 members and basic tier 4 members have the same average salary at each age-yos combo


init_actives_tiers %<>% 
	mutate(
				 nactives_t4_5525   = nactives_t4_basic * share_t4_5525inBasic,
				 salary_t4_5525     = salary_t4_basic ,
				 nactives_t4_basic  = nactives_t4_basic * (1- share_t4_5525inBasic),
				 salary_t4_basic    = salary_t4_basic
				 
	)



init_actives_t6 <- 
	init_actives_tiers %>% 
	select(planname, age, yos, ea, nactives = nactives_t6, salary = salary_t6)

init_actives_t4a <- 
	init_actives_tiers %>% 
	select(planname, age, yos, ea, nactives = nactives_t4_basic, salary = salary_t4_basic)

init_actives_t4b <- 
	init_actives_tiers %>% 
	mutate(nactives_t4b = nactives_t4_5525 + nactives_t4_5527,
				 salary_t4b   = salary_t4_5525   + salary_t4_5527) %>% 
	select(planname, age, yos, ea, nactives = nactives_t4b, salary = salary_t4b)

# x <- init_actives_tiers %>% select(age, yos,nactives_t4_5525 ,  nactives_t4_5527, salary_t4_5525, salary_t4_5527 ) 




